steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    id: Deploy website to GCS
    entrypoint: /bin/sh
    args:
      - '-c'
      - |
        cd client
        gsutil -h "Cache-Control:no-cache,max-age=0" cp -r . gs://agones-golang-wasm.michaelmarkieta.com
        gsutil setmeta -h "Content-Type:application/wasm" gs://agones-golang-wasm.michaelmarkieta.com/main.wasm