steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: Build
    args: [ 'build', '-t', 'gcr.io/agones-golang-wasm/server:$COMMIT_SHA', 'server' ]
  - name: 'gcr.io/cloud-builders/docker'
    id: Push
    args: [ 'push', 'gcr.io/agones-golang-wasm/server:$COMMIT_SHA' ]
  - name: 'gcr.io/cloud-builders/gcloud'
    id: SED
    entrypoint: /bin/sh
    args:
      - '-c'
      - |
        sed -i "s/COMMIT_SHA/${COMMIT_SHA}/g" deployments/gameserver.yaml
  - name: 'gcr.io/cloud-builders/kubectl'
    id: Deploy
    args:
      - 'apply'
      - '-f'
      - 'deployments/gameserver.yaml'
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=northamerica-northeast1-a'
      - 'CLOUDSDK_CONTAINER_CLUSTER=agones'