steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: Build
    args: [ 'build', '-t', 'gcr.io/agones-golang-wasm/server:$COMMIT_SHA', 'internal/server' ]
  - name: 'gcr.io/cloud-builders/docker'
    id: Push
    args: [ 'push', 'gcr.io/agones-golang-wasm/server:$COMMIT_SHA' ]
  - name: 'gcr.io/cloud-builders/gcloud'
    id: SED
    entrypoint: /bin/sh
    args:
      - '-c'
      - |
        sed -i "s/COMMIT_SHA/${COMMIT_SHA}/g" deployments/gameserver.yaml
  - name: 'gcr.io/cloud-builders/gcloud'
    id: Apply
    entrypoint: /bin/sh
    args:
      - '-c'
      - |
        kubectl apply -f deployments/gameserver.yaml
